### PR TITLE
Bugfix/params

### PR DESCRIPTION
**Pull request by JoWilfrid**
Hi there,

You wanted me to come next time with a feature request, so I'm coming with a PR.
Here is what the PR contains:

* As I'm using RVM, I have a `.ruby-version` and `.ruby-gemset` in the project, so I added the `.ruby-gemser` to `.gitignore`
* As it wasn't breaking any test, I upgraded the ruby version from `2.3.0` to `2.4.0` in the `.ruby-version` file
* I added the test case for the improvment/bug fix I wanted
* I added the support for hash parameters in the query string

My problem was I wanted to call an URL with params as following but it wasn't supported:

```
http://anything.tld/endpoint?search[keyword]=foo&search[some_filter]=bar
```

The thing is `CGI.parse` does not support this kind of parameters, so I had to use `Rack::Utils.parse_nested_query`.
Another problem came to me: `Rack::Utils.parse_nested_query` does not support array params with following syntax: `param=foo&param=bar`.

So, I'm using `CGI.parse` to get params as it was, after that, I identify params not parsed as I want to, I isolate them & parse them with `Rack::Utils.parse_nested_query` and I merge everything at the end.

By doing this, we can be compatible with everything.

Hope it will be find for you.

Kind regards,
Johann.

### CODE REVIEW

**Comment by adamluzsi** [comment]
awesome, even an issue about this would had ben ok, but a PR is more than welcomed.  :D

**Comment by JoWilfrid** [comment]
Haha I needed this to be fixed quickly, so I did it, it was the most simple/efficient way.
Wonderful, thank you for the merge, that's cool ! :)

See you in the next issue or PR !

**Comment by adamluzsi** [comment]
@JoWilfrid  you are awesome! I am the one who thanks your efforts!
Please use git link in Gemfile until I find out why the 1.8 build dieing, after that I make a release too! :)

**Comment by adamluzsi** [comment]
I just need to fix my 1.8 env that resist to work with Bundler : /

**Comment by adamluzsi** [comment]
done! :) 
With your preconceived permission, I refactored the code a little and used hash manipulation instead of string manipulation. This was required to fix the bad behavior in 1.8 (+ree) ruby interpreter

**Comment by adamluzsi** [comment]
v6.6.0 released! :) 
Thanks @JoWilfrid again for everything, there is really no words how awesome you are ! :D

**Pull request merged**
