### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by ptolemybarnes**

### CODE REVIEW

**Comment by BlasiusVonSzerencsi** [comment]
Sorry, I really don't want to intrude, but I guess 

> This also implies that the framework does not include extensions like ActiveSupport that monkey patch the whole world.

 would be closer to the intended meaning.

**Comment by adamluzsi** [comment]
Yes , Balázs, could you create a pull request with this , it would be nicer than use your comment without any trace and update the Readme ^~^

**Comment by BlasiusVonSzerencsi** [comment]
Yepp, I've created it.

**Comment by adamluzsi** [comment]
Thank you both for pointing this out in the Readme!
You both helped together us with this! :)

Happy coding.
Adam L.

**Comment by adamluzsi** [comment]
Again @ptolemybarnes you helped, even if this merge was denied, because you successfully pointed out what was miss interpretable in the README.md , and a Great thanks for this! :)

**Pull request closed without merging**
