### PR TITLE
Add multipart support

### PR DESCRIPTION
**Pull request by TheSmartnik**
Hi :wave: 

This pr ads multipart to list of supported formats. Would love to hear your feedback 

@adamluzsi

### CODE REVIEW

**Comment by adamluzsi** [comment]
Hy @TheSmartnik ! :) 
Thanks for your time!

Can you send the content_type parser lookup fix separately where you split and use the first part?

Something puzzled me continuously why I was thinking about the MIME multipart type. 

While this enables to send multiple payload with they own headers, should be handled differently than other serialization formats. This is actually to me is more like an extension of the http protocol by application logic level.

I would like to ask your help to brainstorm this out. I'm currently have the following idea , but this is pretty raw for now.

```ruby
require 'rack/app'

class App < Rack::App

  apply_extensions multipart

  payload do
    parser do
      accept :json, :www_form_urlencoded
     
      on_unknown_media_types do |io|
        io.read
      end
    end
  end

  get '/hello' do
    multipart do
      on 'image/jpeg' do |content|
         # processing logic
      end

      on ‘application/json’ do |obj|
         # processing logic
      end
    end

    “OK”
  end

end
```

My problem here is basically is that payload unserialization scope should be separate from controller logic , but expected protocol requirements maybe still acceptable. But I still feel that we should polish this out. But we definitely get multipart support in rack-app my friend! :)

My other idea was to define this as a endpoint specific middleware where rack env is configured by the logic of how to process it, but I didn't find that any better from this. I was also thinking about redirecting specific chunks to specific endpoints based on class level declaration, but while that would remove a lot of burden from the controller , I'm not sure without a real world use case, that how would it affect processing a request in different controllers sequencially.

```ruby
require 'rack/app'

class App < Rack::App

  apply_extensions multipart

  payload do
    parser do
      accept :json, :www_form_urlencoded
     
      on_unknown_media_types do |io|
        io.read
      end
    end
  end

 # endpoint specific middleware syntax sugar
 multipart do
    process 'image/jpeg', with: post '/x/file.img'
    process ‘application/json’, with:  post '/x/contex'
    # or send it to the target endpoint it self maybe ?
  end
  post '/x' do
    payload # rest comes here I guess after the last separator, if it needed at all in.
    # still questionable
    “OK”
  end

  post '/x/file.img' do
    payload #string from on_unknown_media_types
  end

  post '/x/contex' do
    payload # object
  end
end
```

Tell me, what do you think?
Don't fear say anything about this topic

**Comment by adamluzsi** [comment]
What do you think about this @TheSmartnik ? : )

**Comment by TheSmartnik** [comment]
@adamluzsi sorry to keep you waiting. Had to think about this :)

1. I don't really feel like multipart is somehow different from urlencoded MIME type conceptually. I even think that maybe, it should be default alongside urlencoded MIME type.

2. Multipart doesn't have sub MIME type, like in the code snippets above, rather individual fields do.
More over, it's not necessary that any specific MIME would be sent. It can be generic `application/octet-stream`, even if it's an image. Considering this, what I propose is better params validation. Maybe something like:

```ruby
validate_params do
  required 'spreadsheet', class: File(?), allow: 'text/csv'
end
```

or maybe

```ruby
validate_params do
  required 'file', class: File(?), validator/validate_with: ValidationClass
end
```

What do you think? I believe something like this could be really helpful

**Comment by adamluzsi** [comment]
Just to clarify things, are we talking about this ?
https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

Because than, this is kind a like a protocol over a protocol scenario, where you have a body that actually multiple body combined into one and could include it's own headers / content type.

I checked rack multipart code later to see it clearly. 

I'm sorry if i seems like a hard headed person, but I just want to learn this myself, to see the bigger picture!

**Comment by adamluzsi** [comment]
The validate params are explicitly about query string params, in rack-app, there is no hidden data merge with request body content like in other frameworks. I try to keep the API as close as possible to the http protocol conventions, so who ever learn about rack-app, basically learn the core conventions of the http protocol

**Comment by adamluzsi** [comment]
I'm still open for this discussion, but I close the PR since the build is still broken for it, 
and would break the backward compatibility promise.

**Pull request closed without merging**
