### PR TITLE
Remove Ms. Ruby Image

### PR DESCRIPTION
**Pull request by thefury**
Looks like this image is a pretty clear violation of your code of conduct:

> Examples of unacceptable behavior by participants include the use of sexual language or imagery, derogatory comments or personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct.

### CODE REVIEW

**Comment by adamluzsi** [comment]
This webframework based on Rack, I don't get it clearly , can you specify more about what else could be there than. Maybe "Nice (Ruby Programming Language) Rack (gem)" ?

**Comment by adamluzsi** [comment]
Your opinion is really important to us, and we hope you like our framework, we opened a ticket at Github to ask about this, cause we don't want anyone to feel offended.

I would like to ask some patience until they respond to us. 

Thank you:
Adam

**Comment by thefury** [comment]
Hi Adam,

Thanks for responding.

Any sub-header would work in place of the image The problem is that "Nice Rack", in any of it's forms, is going to be sexually suggestive. Making it a joke because she happens to carrying a rack doesn't change that.

As far as I know, the image and text would be fine according to the Github ToS. The image and text are violating the code of conduct that have been included in *this* repository.

Trevor

**Comment by adamluzsi** [comment]
Thank you for your sharp observation, we remove the new logo and place in the old one where there was no. In the mean time please tell us what is your opinion about the framework and what would be great in your productivity.

Adam

**Pull request merged**
